[package]
name = "freeze-authority-sample-manual"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
borsh = { version = "1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
spel-framework = { git = "https://github.com/mmlado/spel.git", rev = "86fb55e8d174a736cac40d20bc94a6d45df372d6" }
nssa_core = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0", package = "lee_core" }
admin-authority = { git = "https://github.com/mmlado/spel-admin-authority.git", rev = "90b503da538c248edfc872af46a770a456b63089" }
freeze-authority = { path = "../freeze-authority" }

[dev-dependencies]
spel-framework-core = { git = "https://github.com/mmlado/spel.git", rev = "86fb55e8d174a736cac40d20bc94a6d45df372d6", features = ["idl-gen"] }
