[package]
name = "freeze-authority-sample-manual"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
borsh = { version = "1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
spel-framework = { git = "https://github.com/mmlado/spel.git", rev = "7b954dbb572f611fbe5ebaa00b75aaa029803e3b" }
nssa_core = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0", package = "lee_core" }
admin-authority = { git = "https://github.com/mmlado/spel-admin-authority.git", rev = "40a2f81374c519d7b9b40a31e3c74548282ba7f4" }
freeze-authority = { path = "../freeze-authority" }

[dev-dependencies]
spel-framework-core = { git = "https://github.com/mmlado/spel.git", rev = "7b954dbb572f611fbe5ebaa00b75aaa029803e3b", features = ["idl-gen"] }
