[package]
name = "freeze-authority-sample-embedded"
version = "0.1.0"
edition.workspace = true
lints.workspace = true

[dependencies]
borsh = { version = "1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
spel-framework = { git = "https://github.com/mmlado/spel.git", rev = "752d23b01f3d84c03656445d9de43335b7bc780d" }
nssa_core = { git = "https://github.com/logos-blockchain/logos-execution-zone.git", tag = "v0.2.0", package = "lee_core" }
admin-authority = { git = "https://github.com/mmlado/spel-admin-authority.git", rev = "3cafbd74d5af6ba6f76ddf3e529bdb30701c739a" }
freeze-authority = { path = "../freeze-authority" }

[dev-dependencies]
spel-framework-core = { git = "https://github.com/mmlado/spel.git", rev = "752d23b01f3d84c03656445d9de43335b7bc780d", features = ["idl-gen"] }
